DROP TABLE IF EXISTS DatosEventos;
CREATE TABLE DatosEventos (
  id INT unsigned NOT NULL AUTO_INCREMENT,  
  fecha DATETIME NOT NULL,
  gratuito INT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  LONGITUD DECIMAL(11,8) NOT NULL,
  LATITUD DECIMAL(10,8) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

