DROP TABLE IF EXISTS DatosEventos;
CREATE TABLE DatosEventos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,  
  fecha DATETIME NOT NULL,
  gratuito INT NOT NULL,
  titulo VARCHAR(200) NOT NULL,
  longitud DECIMAL(11,8) NOT NULL,
  latitud DECIMAL(10,8) NOT NULL,
  cluster INT UNSIGNED NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

